use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Car {
    pub id: String,
    pub pretty_name: String,
    pub full_name: String,
    pub brand_name: String,
    pub brand_country: String,
    pub year: u32,
    pub car_type: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Track {
    pub id: String,
    pub pretty_name: String,
    pub full_name: String,
    pub country: String,
}

/// Static data for ACC cars
pub fn get_cars() -> HashMap<String, Car> {
    let mut cars = HashMap::new();

    let car_data = vec![
        (
            "alpine_a110_gt4",
            "A110 GT4",
            "Alpine A110 GT4",
            "Alpine",
            "France",
            2018,
            "gt4",
        ),
        (
            "amr_v8_vantage_gt3",
            "V8 Vantage GT3",
            "Aston Martin V8 Vantage GT3",
            "Aston Martin",
            "United Kingdom",
            2019,
            "gt3",
        ),
        (
            "amr_v8_vantage_gt4",
            "V8 Vantage GT4",
            "Aston Martin V8 Vantage GT4",
            "Aston Martin",
            "United Kingdom",
            2019,
            "gt4",
        ),
        (
            "amr_v12_vantage_gt3",
            "V12 Vantage GT3",
            "Aston Martin V12 Vantage GT3",
            "Aston Martin",
            "United Kingdom",
            2013,
            "gt3",
        ),
        (
            "audi_r8_gt4",
            "R8 LMS GT4",
            "Audi R8 LMS GT4",
            "Audi",
            "Germany",
            2017,
            "gt4",
        ),
        (
            "audi_r8_lms",
            "R8 LMS",
            "Audi R8 LMS",
            "Audi",
            "Germany",
            2015,
            "gt3",
        ),
        (
            "audi_r8_lms_evo",
            "R8 LMS Evo",
            "Audi R8 LMS Evo",
            "Audi",
            "Germany",
            2019,
            "gt3",
        ),
        (
            "audi_r8_lms_evo_ii",
            "R8 LMS Evo II",
            "Audi R8 LMS Evo II",
            "Audi",
            "Germany",
            2022,
            "gt3",
        ),
        (
            "audi_r8_lms_gt2",
            "R8 LMS GT2",
            "Audi R8 LMS GT2",
            "Audi",
            "Germany",
            2021,
            "gt2",
        ),
        (
            "bentley_continental_gt3_2016",
            "Continental GT3 '15",
            "Bentley Continental GT3 '15",
            "Bentley",
            "United Kingdom",
            2016,
            "gt3",
        ),
        (
            "bentley_continental_gt3_2018",
            "Continental GT3 '18",
            "Bentley Continental GT3 '18",
            "Bentley",
            "United Kingdom",
            2018,
            "gt3",
        ),
        (
            "bmw_m2_cs_racing",
            "M2 CS Racing",
            "BMW M2 CS Racing",
            "BMW",
            "Germany",
            2020,
            "tcx",
        ),
        (
            "bmw_m4_gt3",
            "M4 GT3",
            "BMW M4 GT3",
            "BMW",
            "Germany",
            2022,
            "gt3",
        ),
        (
            "bmw_m4_gt4",
            "M4 GT4",
            "BMW M4 GT4",
            "BMW",
            "Germany",
            2018,
            "gt4",
        ),
        (
            "bmw_m6_gt3",
            "M6 GT3",
            "BMW M6 GT3",
            "BMW",
            "Germany",
            2017,
            "gt3",
        ),
        (
            "chevrolet_camaro_gt4r",
            "Camaro GT4.R",
            "Chevrolet Camaro GT4.R",
            "Chevrolet",
            "United States",
            2017,
            "gt4",
        ),
        (
            "ferrari_296_gt3",
            "296 GT3",
            "Ferrari 296 GT3",
            "Ferrari",
            "Italy",
            2023,
            "gt3",
        ),
        (
            "ferrari_488_challenge_evo",
            "488 Challenge Evo",
            "Ferrari 488 Challenge Evo",
            "Ferrari",
            "Italy",
            2020,
            "chl",
        ),
        (
            "ferrari_488_gt3",
            "488 GT3",
            "Ferrari 488 GT3",
            "Ferrari",
            "Italy",
            2018,
            "gt3",
        ),
        (
            "ferrari_488_gt3_evo",
            "488 GT3 Evo",
            "Ferrari 488 GT3 Evo",
            "Ferrari",
            "Italy",
            2020,
            "gt3",
        ),
        (
            "ford_mustang_gt3",
            "Mustang GT",
            "Ford Mustang GT3",
            "Ford",
            "United States",
            2024,
            "gt3",
        ),
        (
            "ginetta_g55_gt4",
            "G55 GT4",
            "Ginetta G55 GT4",
            "Ginetta",
            "United Kingdom",
            2012,
            "gt4",
        ),
        (
            "honda_nsx_gt3",
            "NSX GT3",
            "Honda NSX GT3",
            "Honda",
            "Japan",
            2017,
            "gt3",
        ),
        (
            "honda_nsx_gt3_evo",
            "NSX GT3 Evo",
            "Honda NSX GT3 Evo",
            "Honda",
            "Japan",
            2019,
            "gt3",
        ),
        (
            "jaguar_g3",
            "G3",
            "Jaguar G3",
            "Jaguar",
            "United Kingdom",
            2012,
            "gt3",
        ),
        (
            "ktm_xbow_gt2",
            "X-Bow GT2",
            "KTM X-Bow GT2",
            "KTM",
            "Austria",
            2023,
            "gt2",
        ),
        (
            "ktm_xbow_gt4",
            "X-Bow GT4",
            "KTM X-Bow GT4",
            "KTM",
            "Austria",
            2016,
            "gt4",
        ),
        (
            "lamborghini_gallardo_rex",
            "R-EX GT3",
            "Reiter Engineering R-EX GT3",
            "Reiter Engineering",
            "Italy",
            2017,
            "gt3",
        ),
        (
            "lamborghini_huracan_gt3",
            "Huracán GT3",
            "Lamborghini Huracán GT3",
            "Lamborghini",
            "Italy",
            2015,
            "gt3",
        ),
        (
            "lamborghini_huracan_gt3_evo",
            "Huracán GT3 Evo",
            "Lamborghini Huracán GT3 Evo",
            "Lamborghini",
            "Italy",
            2019,
            "gt3",
        ),
        (
            "lamborghini_huracan_gt3_evo2",
            "Huracán GT3 Evo2",
            "Lamborghini Huracán GT3 Evo2",
            "Lamborghini",
            "Italy",
            2023,
            "gt3",
        ),
        (
            "lamborghini_huracan_st",
            "Huracán ST",
            "Lamborghini Huracán Super Trofeo",
            "Lamborghini",
            "Italy",
            2015,
            "st",
        ),
        (
            "lamborghini_huracan_st_evo2",
            "Huracán ST Evo2",
            "Lamborghini Huracán ST Evo2",
            "Lamborghini",
            "Italy",
            2021,
            "st",
        ),
        (
            "lexus_rc_f_gt3",
            "RC F GT3",
            "Lexus RC F GT3",
            "Lexus",
            "Japan",
            2016,
            "gt3",
        ),
        (
            "maserati_mc20_gt2",
            "MC20 GT2",
            "Maserati MC20 GT2",
            "Maserati",
            "Italy",
            2023,
            "gt2",
        ),
        (
            "maserati_mc_gt4",
            "MC GT4",
            "Maserati MC GT4",
            "Maserati",
            "Italy",
            2016,
            "gt4",
        ),
        (
            "mclaren_570s_gt4",
            "570S GT4",
            "McLaren 570S GT4",
            "McLaren",
            "United Kingdom",
            2016,
            "gt4",
        ),
        (
            "mclaren_650s_gt3",
            "650S GT3",
            "McLaren 650S GT3",
            "McLaren",
            "United Kingdom",
            2015,
            "gt3",
        ),
        (
            "mclaren_720s_gt3",
            "720S GT3",
            "McLaren 720S GT3",
            "McLaren",
            "United Kingdom",
            2019,
            "gt3",
        ),
        (
            "mclaren_720s_gt3_evo",
            "720S GT3 Evo",
            "McLaren 720S GT3 Evo",
            "McLaren",
            "United Kingdom",
            2022,
            "gt3",
        ),
        (
            "mercedes_amg_gt2",
            "AMG GT2",
            "Mercedes-AMG GT2",
            "Mercedes-AMG",
            "Germany",
            2023,
            "gt2",
        ),
        (
            "mercedes_amg_gt3",
            "AMG GT3",
            "Mercedes-AMG GT3",
            "Mercedes-AMG",
            "Germany",
            2016,
            "gt3",
        ),
        (
            "mercedes_amg_gt3_evo",
            "AMG GT3 Evo",
            "Mercedes-AMG GT3 Evo",
            "Mercedes-AMG",
            "Germany",
            2020,
            "gt3",
        ),
        (
            "mercedes_amg_gt4",
            "AMG GT4",
            "Mercedes-AMG GT4",
            "Mercedes-AMG",
            "Germany",
            2016,
            "gt4",
        ),
        (
            "nissan_gt_r_gt3_2015",
            "GT-R Nismo GT3 '15",
            "Nissan GT-R Nismo GT3 2017",
            "Nissan",
            "Japan",
            2017,
            "gt3",
        ),
        (
            "nissan_gt_r_gt3_2018",
            "GT-R Nismo GT3 '18",
            "Nissan GT-R Nismo GT3 2018",
            "Nissan",
            "Japan",
            2018,
            "gt3",
        ),
        (
            "porsche_718_cayman_gt4_mr",
            "718 Cayman GT4 MR",
            "Porsche 718 Cayman GT4 Clubsport",
            "Porsche",
            "Germany",
            2019,
            "gt4",
        ),
        (
            "porsche_935",
            "935",
            "Porsche 935",
            "Porsche",
            "Germany",
            2019,
            "gt2",
        ),
        (
            "porsche_991_gt2_rs_mr",
            "991 II GT2 RS CS EVO",
            "Porsche 991 II GT2 RS CS EVO",
            "Porsche",
            "Germany",
            2023,
            "gt2",
        ),
        (
            "porsche_991_gt3_r",
            "991 GT3 R",
            "Porsche 991 GT3 R",
            "Porsche",
            "Germany",
            2016,
            "gt3",
        ),
        (
            "porsche_991ii_gt3_cup",
            "991 II GT3 Cup",
            "Porsche 991.2 GT3 Cup",
            "Porsche",
            "Germany",
            2017,
            "cup",
        ),
        (
            "porsche_991ii_gt3_r",
            "991 II GT3 R",
            "Porsche 991.2 GT3 R",
            "Porsche",
            "Germany",
            2019,
            "gt3",
        ),
        (
            "porsche_992_gt3_cup",
            "992 GT3 Cup",
            "Porsche 992 GT3 Cup",
            "Porsche",
            "Germany",
            2021,
            "cup",
        ),
        (
            "porsche_992_gt3_r",
            "992 GT3 R",
            "Porsche 992 GT3 R",
            "Porsche",
            "Germany",
            2023,
            "gt3",
        ),
    ];

    for (id, pretty_name, full_name, brand_name, brand_country, year, car_type) in car_data {
        cars.insert(
            id.to_string(),
            Car {
                id: id.to_string(),
                pretty_name: pretty_name.to_string(),
                full_name: full_name.to_string(),
                brand_name: brand_name.to_string(),
                brand_country: brand_country.to_string(),
                year,
                car_type: car_type.to_string(),
            },
        );
    }

    cars
}

/// Static data for ACC tracks
pub fn get_tracks() -> HashMap<String, Track> {
    let mut tracks = HashMap::new();

    let track_data = vec![
        (
            "Barcelona",
            "Barcelona",
            "Circuit de Barcelona-Catalunya",
            "Spain",
        ),
        (
            "brands_hatch",
            "Brands Hatch",
            "Brands Hatch Circuit",
            "United Kingdom",
        ),
        ("cota", "COTA", "Circuit of The Americas", "United States"),
        (
            "donington",
            "Donington Park",
            "Donington Park",
            "United Kingdom",
        ),
        ("Hungaroring", "Hungaroring", "Hungaroring", "Hungary"),
        ("Imola", "Imola", "Autodromo Enzo e Dino Ferrari", "Italy"),
        (
            "indianapolis",
            "Indianapolis",
            "Indianapolis Motor Speedway",
            "United States",
        ),
        (
            "Kyalami",
            "Kyalami",
            "Kyalami Grand Prix Circuit",
            "South Africa",
        ),
        (
            "Laguna_Seca",
            "Laguna Seca",
            "WeatherTech Raceway Laguna Seca",
            "United States",
        ),
        ("misano", "Misano", "Misano World Circuit", "Italy"),
        ("monza", "Monza", "Monza Circuit", "Italy"),
        (
            "mount_panorama",
            "Mount Panorama",
            "Mount Panorama Circuit",
            "Australia",
        ),
        (
            "nurburgring",
            "Nürburgring",
            "Nürburgring-Nordschleife",
            "Germany",
        ),
        (
            "nurburgring_24h",
            "Nürburgring 24h",
            "Nürburgring 24h Circuit (Nordschleife)",
            "Germany",
        ),
        (
            "oulton_park",
            "Oulton Park",
            "Oulton Park",
            "United Kingdom",
        ),
        (
            "Paul_Ricard",
            "Paul Ricard",
            "Circuit Paul Ricard",
            "France",
        ),
        (
            "Silverstone",
            "Silverstone",
            "Silverstone",
            "United Kingdom",
        ),
        (
            "snetterton",
            "Snetterton",
            "Snetterton Circuit",
            "United Kingdom",
        ),
        ("Spa", "Spa", "Circuit de Spa-Francorchamps", "Belgium"),
        ("Suzuka", "Suzuka", "Suzuka Circuit", "Japan"),
        (
            "Valencia",
            "Valencia",
            "Circuit Ricardo Tormo Valencia",
            "Spain",
        ),
        (
            "watkins_glen",
            "Watkins Glen",
            "Watkins Glen International",
            "United States",
        ),
        ("Zandvoort", "Zandvoort", "Circuit Zandvoort", "Netherlands"),
        ("Zolder", "Zolder", "Circuit Zolder", "Belgium"),
        ("red_bull_ring", "Red Bull Ring", "Red Bull Ring", "Austria"),
    ];

    for (id, pretty_name, full_name, country) in track_data {
        tracks.insert(
            id.to_string(),
            Track {
                id: id.to_string(),
                pretty_name: pretty_name.to_string(),
                full_name: full_name.to_string(),
                country: country.to_string(),
            },
        );
    }

    tracks
}

/// Helper function to find car by folder name
pub fn find_car_by_folder(folder_name: &str) -> Option<Car> {
    get_cars().into_values().find(|car| car.id == folder_name)
}

/// Helper function to find track by folder name
pub fn find_track_by_folder(folder_name: &str) -> Option<Track> {
    get_tracks()
        .into_values()
        .find(|track| track.id == folder_name)
}
